### ISSUE TITLE
"ncmpcpp toggle" "ncmpcpp prev" "ncmpcpp next" they don't work anymore ?

### ISSUE THREAD

**Issue by hillz1** [arybczak/ncmpcpp#123]
In nmcpcpp 0.4 those options still work but now I'm on ncmpcpp 0.7.3 those commands don't work anymore, did you get rid of those options ? I want to be able to switch between songs and play / pause with system wide keyboard shortcuts but unfortunately those commands don't work anymore.

**Comment by arybczak** [comment]
See http://rybczak.net/ncmpcpp/faq/.

**Comment by silbe** [comment]
It would be nice if this would be mentioned in `NEWS`. I was quite surprised by this and couldn't figure out what was going on at first because the removal is completely undocumented (or at least not documented in a way that I would have found it even after suspecting that this feature had been removed).
