### ISSUE TITLE
Back to ncmpc

### ISSUE THREAD

**Issue by hategeek68** [arybczak/ncmpcpp#26]
I cannot remove songs anymore (d used to work) ... and i cannot even access the help screen to check the new keybindings. 

A big fiasco.

What is wrong with the free community is that they never thing about users or market, that's why they failed. I remember Gnome3 fiasco, and pulseaudio that gave me headaches (since i was using digital sound output toward a DAC it was not standard in those days ... )

I used to love ncmcppp, because i lover curse interfaces, they are efficients. 

I will probably switch to pms or find an emacs mode ;-(

Note that use a MAC OX terminal so it may cause the issues. 

I use that :
ncmpcpp  --version
ncmpcpp 0.6.2_pre

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info

encoding detection: enabled
built with support for: curl ncurses taglib unicode

**Comment by trygveaa** [comment]
People don't like change, but an application needs to be able to change in order to improve. After I got used to the new key bindings, I actually like them better. I think they are more practical than the old, but of course that is subjective.

The help screen is F1. But if you don't want to learn new key bindings, you can always rebind them to the old ones.

**Comment by arybczak** [comment]
Man page was appropriately updated to reflect the changes, so if you checked it out, you wouldn't need to write that.

> People don't like change, but an application needs to be able to change in order to improve.

This.

Granted, the execution could have been much better by providing a complete change log (which I'm now keeping track of), but that's what you get by not doing any release for 2 years :(
