### ISSUE TITLE
album artist not recognized in ncmpcpp

### ISSUE THREAD

**Issue by mnpqraven** [arybczak/ncmpcpp#317]
Hi, i have been configuring ncmpcpp for a while and the player is not reading album artist metadata correctly while other players can. Anyone has an idea where the problem could be ?
Here are the examples of ncmpcpp and Clementine, ncmpcpp shows album artists as <empty> while clementine shows them correctly
ncmpcpp:
![](https://i.imgur.com/2BASHZ8.png)
clementine:
![](https://i.imgur.com/oPIiLGv.png)
here are my mpd.conf and ncmpcpp conf file
````
music_directory     "~/Music"
playlist_directory  "~/Playlists"
db_file             "~/.local/share/mpd/mpd.db"
log_file            "~/.local/share/mpd/mpd.log"
pid_file            "~/.local/share/mpd/mpd.pid"
state_file          "~/.local/share/mpd/mpd.state"
sticker_file        "~/.local/share/mpd/sticker.sql"

bind_to_address     "127.0.0.1"
log_level           "default"
restore_paused      "yes"
metadata_to_use     "artist,album,title,track,date"
auto_update         "yes"

audio_output {
    type        "pulse"
    name        "pulse audio"
}

audio_output {
    type        "fifo"
    name        "mpd_fifo"
    path        "/tmp/mpd.fifo"
    format      "44100:16:2"
}
````

````
ncmpcpp_directory = ~/.config/ncmpcpp
lyrics_directory = ~/Music
# lyrics saved in music dir, see store_lyrics_in_song_dir
mpd_music_dir = ~/Music


colors_enabled = yes
empty_tag_color = 240
header_window_color = white
volume_color = 13
state_line_color = white
state_flags_color = 138
main_window_color = white
color1 = white
color2 = red
main_window_highlight_color = white
progressbar_color = 234
progressbar_elapsed_color = white
statusbar_color = 240
alternative_ui_separator_color = white
active_column_color = 138


song_list_format = {%A - }{%t}|{$8%f$9}$R{$3(%l)$9}
#
song_status_format = {{%a{ "%b"{ (%y)}} - }{%t}}|{%f}
#
song_library_format = {%n - }{%t}|{%f}
#
alternative_header_first_line_format = $b$1$aqqu$/a$9 {%t}|{%f} $1$atqq$/a$9$/b
#
alternative_header_second_line_format = {{$4$b%a$/b$9}{ - $7%b$9}{ ($4%y$9)}}|{%D}
#
current_item_prefix = $(yellow)$r
#
current_item_suffix = $/r$(end)
#
current_item_inactive_column_prefix = $(white)$r
#
current_item_inactive_column_suffix = $/r$(end)
#
now_playing_prefix = $b
#
now_playing_suffix = $/b
#
browser_playlist_prefix = "$2playlist$9 "
#
selected_item_prefix = $6
#
selected_item_suffix = $9
#
modified_item_prefix = $3> $9
#
##
## Note: attributes are not supported for the following variables.
##
song_window_title_format = {%A - }{%t}|{%f}
##
## Note: Below variables are used for sorting songs in browser.  The sort mode
## determines how songs are sorted, and can be used in combination with a sort
## format to specify a custom sorting format.  Available values for
## browser_sort_mode are "name", "mtime", "format" and "noop".
##
#
browser_sort_mode = name
#
browser_sort_format = {%A - }{%t}|{%f} {(%l)}
song_columns_list_format = (20)[]{A} (6f)[green]{NE} (50)[white]{t|f:Title} (20)[cyan]{b} (7f)[magenta]{l}
````

**Comment by mnpqraven** [comment]
also it's not just album artist, some other metadata are also missing from ncmpcpp
![](https://i.imgur.com/68Bh4B3.png)

**Comment by mnpqraven** [comment]
update: problem solved
for vorbis/flac libraries you probably need these lines in the mpd conf
````
filesystem_charset    "UTF-8"
id3v1_encoding        "UTF-8"
````

**Comment by alan12345678** [comment]
Aah... I'm having serious trouble too with "albumartist". It doesn't work - I've spent DAYS configuring.

To note though: I use exclusively UTF-8. Running ncmpcpp on an Arch based distro, and the disk for my music library is ext4 because it allows me to use UTF-8 and include special chars in filenames :) So it's important to note perhaps that this music library has never been anywhere near Windows.

I did my tagging with kid3. I notice that if I open a music file (typically an mp3) I notice that at ID3v1..1 tags there is NO field at all for "album artist". Nothing. This might explain something. However, my library is tagged with both these and ID3v2.3, which of course carries the full fields.

I don't mind re-tagging or adding additional tags, but can anyone please explain to me which part of the replay chain is failing to pick up the 3.2 tags? Is it mpd? Is it a fault in my tagger? Should ID3v.1.1 have "album artist" fields?

Obviously it's a critical distinction for many of us - that the music is displayed first and foremost by "album artist", with "artist" appearing within an album selection.
