### ISSUE TITLE
ncmpcpp keeps hitting the DNS for no good reason

### ISSUE THREAD

**Issue by untitaker** [arybczak/ncmpcpp#37]
This is the same as http://bugs.musicpd.org/view.php?id=3926, refiled here because GitHub seems to be the preferred bugtracker now:

  1. Have own DNS server or cache which has a "static" entry for a specific hostname, pointing to the IP of the MPD server.

  2. Point ncmpcpp to that hostname.

  3. Open ncmpcpp.

  4. Open the request logs for the DNS server, notice many requests to mentioned hostname

  5. Close ncmpcpp, the requests stop

The maintainer of libmpdclient [didn't know what I was talking about](http://bugs.musicpd.org/view.php?id=4075), so I think more direct talk between `unK_` and `cirrus` about the way ncmpcpp uses libmpdclient is required.

**Comment by arybczak** [comment]
> GitHub seems to be the preferred bugtracker now:

That is not true.

Please do not duplicate issues. As I said, ncmpcpp doesn't do any low-level networking by itself. Maybe that's curl's fault, so if you want to be sure, recompile ncmpcpp without curl support and check then. If the requests stop, reopen the issue on mantis. If they don't, well, you need to provide evidence that's ncmpcpp's fault, because unfortunately I have no way to replicate this issue.

**Comment by untitaker** [comment]
>That is not true. Please do not duplicate issues.

Ok. Which one is, or should be?

I did not know that you have no way of reproducing this issue, so I was fairly irritated that I, as an end user, should provide details to the libmpdclient that I don't even have. I'll try to figure out how to compile ncmpcpp without curl, but I really can't guess how ncmpcpp does networking under the hood.

**Comment by arybczak** [comment]
> Ok. Which one is, or should be?

http://bugs.musicpd.org/view.php?id=3926

**Comment by untitaker** [comment]
I meant, which bugtracker is preferred in general.

**Comment by arybczak** [comment]
Mantis.
