### ISSUE TITLE
In INSTALL, `configure` is mentioned, which does not exist

### ISSUE THREAD

**Issue by czipperz** [arybczak/ncmpcpp#86]
> 1. `cd` to the directory containing the package's source code and type
>     `./configure` to configure the package for your system.  If you're
>     using `csh` on an old version of System V, you might need to type
>     `sh ./configure` instead to prevent `csh` from trying to execute
>     `configure` itself.

Should it be changed to `./configure.ac`?  Or should `configure.ac` be renamed to `configure`?

Running `./configure && make && make install` is the standard way to install software on Linux, so I think the second choice is better for consistency with other software.

**Comment by entd** [comment]
Use ./autogen first

**Comment by czipperz** [comment]
I know, but the INSTALL guide should still be updated.

**Comment by arybczak** [comment]
Can you provide a patch?

**Comment by czipperz** [comment]
I tried to rename autogen.sh to configure but it then didn't work as autogen.sh generates a configure script... which it then runs... which kills it :(

**Comment by JeromeBon** [comment]
The INSTALL guide refere to autoconf which is now autogen. And the step 1 is outdated since autogen execute ./configure after is creation.
I think I can provide a patch to update the INSTALL guide.

Since I'm a beginner github user I'm not sure posting this comment before a PR was usefull, so let me know if I'm doing this wrong.

**Comment by arybczak** [comment]
It's fine, no worries.

**Comment by arybczak** [comment]
0156e7d42417d156f37c3963fd661e57f5d8de97
