### ISSUE TITLE
Fallback config locations

### ISSUE THREAD

**Issue by rychipman** [arybczak/ncmpcpp#88]
it would be nice if ncmpcpp would look for its config in ~/.config/ncmpcpp/config if nothing is found in ~/.ncmpcpp/config

**Comment by arybczak** [comment]
It does (in 0.7).

**Comment by k0ral** [comment]
There is an odd behavior though: I have `~/.ncmpcpp` symlinked to `~/.config/ncmpcpp`, and since 0.7 release, the configuration file is read twice, leading to errors because of duplicated entries.
It looks like `ncmpcpp` tries to load configuration from both path in a non-exclusive way. If that's intended, could you please document it explicitly in the manual (and release notes for bonus points) ?

**Comment by arybczak** [comment]
It's documented in the output of ncmpcpp --help.
